Pipeline editor nearly fixed
I have resolved most of the errors currently in the pipeline editor however I got stuck attempting to fix the error:  error TS2322: Type '{ children: Element[]; theme: any; }' is not assignable to type 'IntrinsicAttributes & { theme: DeepPartial<Theme>; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { theme: DeepPartial<Theme>; }'.